#!/usr/bin/env python3
"""Generates database/seed.sql.

The data is built rather than typed because every report has to return at least
five rows, and several need specific shapes: members who have only ever played
goalkeeper, members who never won, members who play FIFA but are never assigned
to a formation. Those are the cohort flags below.

The random seed is fixed, so re-running produces the same SQL.
"""

import random
from datetime import date, datetime, timedelta

random.seed(353)

TODAY = date(2026, 8, 4)
OUT = []


def w(s=""):
    OUT.append(s)


def q(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, datetime):
        return "'" + v.strftime("%Y-%m-%d %H:%M:%S") + "'"
    if isinstance(v, date):
        return "'" + v.isoformat() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def rows(table, cols, data, chunk=200):
    if not data:
        return
    for i in range(0, len(data), chunk):
        part = data[i:i + chunk]
        w(f"INSERT INTO {table} ({', '.join(cols)}) VALUES")
        w(",\n".join("  (" + ", ".join(q(v) for v in r) + ")" for r in part) + ";")
        w()


# Name pools
FIRST_M = ["Liam", "Noah", "William", "Thomas", "Felix", "Adam", "Nathan", "Leo",
           "Jacob", "Antoine", "Samuel", "Olivier", "Emile", "Raphael", "Hugo",
           "Elias", "Malik", "Diego", "Kai", "Mateo", "Owen", "Zane", "Rowan",
           "Theo", "Jonas", "Aleks", "Ravi", "Ibrahim", "Ethan", "Marc"]
FIRST_F = ["Emma", "Olivia", "Alice", "Charlotte", "Livia", "Rose", "Zoe", "Mia",
           "Chloe", "Juliette", "Sofia", "Leane", "Maya", "Amelia", "Nora",
           "Ines", "Anaya", "Priya", "Yuki", "Elena", "Clara", "Nadia", "Iris",
           "Talia", "Sana", "Freya", "Camila", "Ayla", "Lucia", "Hana"]
LAST = ["Tremblay", "Gagnon", "Roy", "Cote", "Bouchard", "Gauthier", "Morin",
        "Lavoie", "Fortin", "Gagne", "Ouellet", "Pelletier", "Belanger",
        "Levesque", "Bergeron", "Leblanc", "Paquette", "Girard", "Simard",
        "Boucher", "Caron", "Beaulieu", "Cloutier", "Dube", "Poirier",
        "Fournier", "Lapointe", "Leclerc", "Nadeau", "Thibault", "Okafor",
        "Nguyen", "Haddad", "Silva", "Kaur", "Rossi", "Novak", "Petrov"]

ssn_seq = iter(range(100000001, 100009999))
med_seq = iter(range(500000001, 500009999))


def next_ssn():
    n = next(ssn_seq)
    return f"{n // 10000000}{(n // 1000) % 10000:04d}-{n % 1000:03d}"[:11]


def next_med():
    return f"MC{next(med_seq)}"


def addr(i, city):
    return f"{100 + i * 7} rue {random.choice(['Sherbrooke','Laurier','Papineau','Bernard','Cartier','Beaubien','Rachel'])}"


def postal(i):
    return f"H{i % 9 + 1}{chr(65 + i % 26)} {i % 9 + 1}{chr(65 + (i * 3) % 26)}{i % 9 + 1}"


w("-- Sample data. Generated by database/generate_seed.py - edit that, not this.")
w("--")
w("-- Loaded after triggers.sql on purpose: every row here passes the three-hour")
w("-- rule, the gender rule, the location rule and the unpaid-fees rule, so a")
w("-- clean load shows the constraints work.")
w("--")
w("-- Sized so every report returns at least five rows on a fresh database.")
w()
w("SET FOREIGN_KEY_CHECKS = 0;")
w("TRUNCATE TABLE Game_Participation; TRUNCATE TABLE FIFA_Games;")
w("TRUNCATE TABLE EmailLogs; TRUNCATE TABLE FormationPlayers;")
w("TRUNCATE TABLE TeamFormations; TRUNCATE TABLE Sessions;")
w("TRUNCATE TABLE Team_Members; TRUNCATE TABLE Teams;")
w("TRUNCATE TABLE Member_Hobby; TRUNCATE TABLE Hobbies;")
w("TRUNCATE TABLE Payments; TRUNCATE TABLE FamilyRelationship;")
w("TRUNCATE TABLE Family_Location_History; TRUNCATE TABLE Member_Location_History;")
w("TRUNCATE TABLE Personnel_Assignment; TRUNCATE TABLE ClubMembers;")
w("TRUNCATE TABLE FamilyMembers; TRUNCATE TABLE Location_Phones;")
w("TRUNCATE TABLE Locations; TRUNCATE TABLE Personnel;")
w("SET FOREIGN_KEY_CHECKS = 1;")
w()

# Locations
LOC_DEFS = [
    (1, "Montreal Head Office", "Head",   "1200 boulevard De Maisonneuve", "Montreal",   "QC", "H3A 1J5", 400),
    (2, "Laval Branch",         "Branch", "455 boulevard Saint-Martin",    "Laval",      "QC", "H7M 2A1", 250),
    (3, "Longueuil Branch",     "Branch", "88 chemin de Chambly",          "Longueuil",  "QC", "J4H 3L7", 220),
    (4, "Quebec Branch",        "Branch", "310 rue Saint-Jean",            "Quebec",     "QC", "G1R 1N5", 240),
    (5, "Sherbrooke Branch",    "Branch", "77 rue King Ouest",             "Sherbrooke", "QC", "J1H 1N9", 180),
    (6, "Gatineau Branch",      "Branch", "140 boulevard Maloney",         "Gatineau",   "QC", "J8P 1E1", 200),
]
loc_rows, phone_rows = [], []
for lid, name, typ, address, city, prov, pc, cap in LOC_DEFS:
    web = "https://www.countrysoccerclub.ca/" + name.split()[0].lower()
    loc_rows.append([lid, name, typ, address, city, prov, pc, web, cap, None])
    phone_rows.append([lid, f"514-555-{1000 + lid * 11:04d}"])
    if lid % 2 == 1:
        phone_rows.append([lid, f"438-555-{2000 + lid * 13:04d}"])

rows("Locations",
     ["locationID", "name", "type", "address", "city", "province", "postalCode",
      "webAddress", "capacity", "managerID"], loc_rows)
rows("Location_Phones", ["locationID", "phone"], phone_rows)

# Personnel
#   Each location gets a manager, coaches, an assistant coach, a captain and
#   one other. The head location also gets a deputy manager, treasurer and
#   secretary. Dual-role people are also FamilyMembers, matched on SSN, which
#   reports 17 and 19 need. They are all coaches and mostly volunteers.
personnel = []       # dicts
pid = 0
managers = {}
coaches_by_loc = {lid: [] for lid, *_ in LOC_DEFS}
dual_role = []       # personnel dicts that will also be FamilyMembers


def add_personnel(loc, role, mandate, title=None, dual=False, gender_pool=None):
    global pid
    pid += 1
    fn = random.choice(FIRST_M if (gender_pool or pid) % 2 else FIRST_F)
    ln = random.choice(LAST)
    city = [d[4] for d in LOC_DEFS if d[0] == loc][0]
    p = dict(id=pid, firstName=fn, lastName=ln,
             DOB=date(random.randint(1968, 1994), random.randint(1, 12), random.randint(1, 28)),
             SSN=next_ssn(), med=next_med(),
             tel=f"514-555-{3000 + pid:04d}",
             address=addr(pid, city), city=city, province="QC", postalCode=postal(pid),
             email=f"{fn.lower()}.{ln.lower()}{pid}@cscs.ca",
             role=role, mandate=mandate, title=title, loc=loc)
    personnel.append(p)
    if role in ("Coach", "Assistant Coach"):
        coaches_by_loc[loc].append(p)
    if dual:
        dual_role.append(p)
    return p


for lid, name, typ, *_ in LOC_DEFS:
    mgr = add_personnel(lid, "Administrator", "Salaried",
                        "President / General Manager" if typ == "Head" else "General Manager")
    managers[lid] = mgr["id"]
    if typ == "Head":
        add_personnel(lid, "Administrator", "Salaried", "Deputy Manager")
        add_personnel(lid, "Administrator", "Salaried", "Treasurer")
        add_personnel(lid, "Administrator", "Volunteer", "Secretary")
        add_personnel(lid, "Administrator", "Volunteer", "Administrator")
    # coaches - the first two at every location are dual-role volunteers
    add_personnel(lid, "Coach", "Volunteer", "Head Coach", dual=True)
    add_personnel(lid, "Coach", "Volunteer", "Head Coach", dual=True)
    add_personnel(lid, "Coach", "Volunteer", "Head Coach", dual=True)
    add_personnel(lid, "Coach", "Salaried", "Head Coach")
    add_personnel(lid, "Assistant Coach", "Volunteer")
    add_personnel(lid, "Captain", "Volunteer")
    add_personnel(lid, "Other", "Salaried", "Groundskeeper")

rows("Personnel",
     ["personnelID", "firstName", "lastName", "DOB", "SSN", "medicareNo",
      "telephone", "address", "city", "province", "postalCode", "email",
      "role", "mandate", "title"],
     [[p["id"], p["firstName"], p["lastName"], p["DOB"], p["SSN"], p["med"],
       p["tel"], p["address"], p["city"], p["province"], p["postalCode"],
       p["email"], p["role"], p["mandate"], p["title"]] for p in personnel])

w("-- Managers of each location (deferred because Locations and Personnel are")
w("-- mutually referential).")
for lid in managers:
    w(f"UPDATE Locations SET managerID = {managers[lid]} WHERE locationID = {lid};")
w()

# Personnel assignments. A few people have an earlier, closed assignment
# somewhere else, to exercise the temporal history.
pa = []
for p in personnel:
    if p["id"] % 7 == 0:
        other = 1 + (p["loc"] % 6)
        pa.append([p["id"], other, date(2022, 1, 15), date(2022, 6, 30)])
    pa.append([p["id"], p["loc"], date(2023, 1, 9), None])
rows("Personnel_Assignment", ["personnelID", "locationID", "startDate", "endDate"], pa)

# Hobbies
HOBBIES = ["Soccer", "Volleyball", "Tennis", "Ping pong", "Swimming", "Hockey",
           "Golf", "Basketball", "Cycling", "Chess"]
rows("Hobbies", ["hobbyID", "hobbyName"], [[i + 1, h] for i, h in enumerate(HOBBIES)])

# Club members
#
# 24 per location, 12 boys and 12 girls. Cohorts are spread across locations so
# every report has rows at more than one.
members = []
mid = 999
PER_LOC = 24


def make_member(loc, gender, age, joined_as_minor=False, active=True):
    global mid
    mid += 1
    fn = random.choice(FIRST_M if gender == "Boys" else FIRST_F)
    ln = random.choice(LAST)
    city = [d[4] for d in LOC_DEFS if d[0] == loc][0]
    dob = date(TODAY.year - age, random.randint(1, 12), random.randint(1, 28))
    if dob > TODAY.replace(year=TODAY.year - age):
        dob = dob.replace(month=1, day=5)
    if joined_as_minor:
        reg_year = TODAY.year - (age - 15)          # registered around age 15
    else:
        reg_year = TODAY.year - random.randint(1, min(4, max(1, age - 4)))
    reg = date(reg_year, random.randint(1, 9), random.randint(1, 28))
    if reg < date(dob.year + 4, dob.month, dob.day):
        reg = date(dob.year + 4, dob.month, dob.day) + timedelta(days=30)
    m = dict(id=mid, firstName=fn, lastName=ln, DOB=dob, gender=gender,
             height=round(random.uniform(110, 190), 1),
             weight=round(random.uniform(22, 88), 1),
             SSN=next_ssn(), med=next_med(),
             phone=f"514-555-{6000 + mid % 3000:04d}",
             email=f"{fn.lower()}.{ln.lower()}{mid}@example.ca",
             address=addr(mid, city), city=city, province="QC",
             postalCode=postal(mid), reg=reg, loc=loc, age=age,
             active=active, joined_as_minor=joined_as_minor,
             only_gk=False, never_formation=False, never_wins=False,
             all_five_roles=False, fifa_heavy=False)
    members.append(m)
    return m


for lid, *_ in LOC_DEFS:
    for gender in ("Boys", "Girls"):
        for k in range(12):
            # ages: mostly minors, a handful of majors
            if k < 8:
                age = random.randint(8, 17)
                jam = False
            else:
                age = random.randint(18, 34)
                jam = (k >= 10)          # 2 per gender per location joined as minors
            make_member(lid, gender, age, joined_as_minor=jam)

# Extra members who play FIFA but are never assigned to a formation.
for lid in (1, 2, 3, 4, 5, 6):
    m = make_member(lid, "Boys" if lid % 2 else "Girls", random.randint(12, 20))
    m["never_formation"] = True

# Two members with 2025 unpaid, so the integrity demo has someone to reject and
# report 14 shows both statuses.
inactive_members = []
for lid in (1, 3):
    m = make_member(lid, "Boys", random.randint(19, 26), joined_as_minor=True)
    m["active"] = False
    m["never_formation"] = True          # the trigger would refuse them anyway
    inactive_members.append(m)

# Cohort flags
by_loc_gender = {}
for m in members:
    if m["never_formation"]:
        continue
    by_loc_gender.setdefault((m["loc"], m["gender"]), []).append(m)

for i, lid in enumerate([1, 2, 3, 4, 5, 6]):
    pool = by_loc_gender[(lid, "Boys")]
    pool[0]["only_gk"] = True                    # report 15
    pool[1]["all_five_roles"] = True             # report 16
    pool[2]["never_wins"] = True                 # report 18
    pool[3]["never_wins"] = True
    gpool = by_loc_gender[(lid, "Girls")]
    gpool[0]["only_gk"] = True
    gpool[1]["all_five_roles"] = True
    gpool[2]["never_wins"] = True

rows("ClubMembers",
     ["memberID", "firstName", "lastName", "DOB", "gender", "height", "weight",
      "SSN", "medicareNo", "phone", "email", "address", "city", "province",
      "postalCode", "registrationDate"],
     [[m["id"], m["firstName"], m["lastName"], m["DOB"], m["gender"], m["height"],
       m["weight"], m["SSN"], m["med"], m["phone"], m["email"], m["address"],
       m["city"], m["province"], m["postalCode"], m["reg"]] for m in members])

# Location history. A few members transferred branch so the endDate IS NULL
# filter has something to filter out.
mlh = []
for m in members:
    if m["id"] % 11 == 0:
        other = 1 + (m["loc"] % 6)
        mlh.append([m["id"], other, m["reg"], m["reg"] + timedelta(days=200)])
        mlh.append([m["id"], m["loc"], m["reg"] + timedelta(days=201), None])
    else:
        mlh.append([m["id"], m["loc"], m["reg"], None])
rows("Member_Location_History", ["memberID", "locationID", "startDate", "endDate"], mlh)

# Hobbies
mh = []
for m in members:
    for h in random.sample(range(1, len(HOBBIES) + 1), random.randint(0, 3)):
        mh.append([m["id"], h])
rows("Member_Hobby", ["memberID", "hobbyID"], mh)

# Family members
#   Every minor gets a primary family member. The dual-role coaches are family
#   members themselves, sharing an SSN with their Personnel row.
families = []
fid = 0


def make_family(loc, ftype="Primary", person=None):
    global fid
    fid += 1
    if person:
        f = dict(id=fid, firstName=person["firstName"], lastName=person["lastName"],
                 DOB=person["DOB"], SSN=person["SSN"], med=next_med(),
                 phone=person["tel"], address=person["address"], city=person["city"],
                 province="QC", postalCode=person["postalCode"], email=person["email"],
                 ftype=ftype, loc=loc)
    else:
        fn = random.choice(FIRST_M + FIRST_F)
        ln = random.choice(LAST)
        city = [d[4] for d in LOC_DEFS if d[0] == loc][0]
        f = dict(id=fid, firstName=fn, lastName=ln,
                 DOB=date(random.randint(1972, 1992), random.randint(1, 12), random.randint(1, 28)),
                 SSN=next_ssn(), med=next_med(),
                 phone=f"514-555-{7000 + fid:04d}", address=addr(fid, city),
                 city=city, province="QC", postalCode=postal(fid),
                 email=f"{fn.lower()}.{ln.lower()}.fam{fid}@example.ca",
                 ftype=ftype, loc=loc)
    families.append(f)
    return f


# dual-role first, so they get low familyIDs and are easy to spot in a demo
dual_families = {}
for p in dual_role:
    f = make_family(p["loc"], "Primary", person=p)
    dual_families[p["id"]] = f

# ordinary primary family members: one per 2 minors at each location
minors_by_loc = {}
for m in members:
    if m["age"] < 18:
        minors_by_loc.setdefault(m["loc"], []).append(m)

frel = []
REL = ["Father", "Mother", "Grandfather", "Grandmother", "Tutor", "Partner", "Friend", "Other"]
for lid, minors in minors_by_loc.items():
    random.shuffle(minors)
    # the two dual-role coaches at this location each take 3 minors, so they
    # are family members of minors (report 19) and head coaches (report 17)
    duals = [dual_families[p["id"]] for p in dual_role if p["loc"] == lid]
    idx = 0
    for f in duals:
        for _ in range(2):
            if idx < len(minors):
                mm = minors[idx]; idx += 1
                frel.append([f["id"], mm["id"], mm["reg"], None, random.choice(REL[:4])])
                mm["family"] = f["id"]
    while idx < len(minors):
        f = make_family(lid, "Primary")
        for _ in range(min(3, len(minors) - idx)):
            mm = minors[idx]; idx += 1
            frel.append([f["id"], mm["id"], mm["reg"], None, random.choice(REL[:4])])
            mm["family"] = f["id"]
        # a Secondary family member for some of them, to exercise familyType
        if fid % 3 == 0:
            f2 = make_family(lid, "Secondary")
            frel.append([f2["id"], mm["id"], mm["reg"] + timedelta(days=10), None, "Other"])

rows("FamilyMembers",
     ["familyID", "firstName", "lastName", "DOB", "SSN", "medicareNo", "phone",
      "address", "city", "province", "postalCode", "email", "familyType"],
     [[f["id"], f["firstName"], f["lastName"], f["DOB"], f["SSN"], f["med"],
       f["phone"], f["address"], f["city"], f["province"], f["postalCode"],
       f["email"], f["ftype"]] for f in families])

rows("Family_Location_History", ["familyID", "locationID", "startDate", "endDate"],
     [[f["id"], f["loc"], date(2023, 1, 1), None] for f in families])

rows("FamilyRelationship",
     ["familyID", "memberID", "startDate", "endDate", "relationshipType"], frel)

# Payments
#   Every active member pays 2025 in full over 1-4 installments. A few overpay,
#   which becomes a donation. Inactive members underpay.
pay = []
pay_id = 0
for m in members:
    for year in range(max(m["reg"].year, 2024), 2027):
        age_at_year = year - m["DOB"].year
        fee = 200 if age_at_year >= 18 else 100
        if not m["active"] and year == 2025:
            total = fee / 2                       # deliberately short -> Inactive
        elif m["id"] % 13 == 0:
            total = fee + 50                      # donation
        else:
            total = fee
        n = random.randint(1, 4)
        base = round(total / n, 2)
        for k in range(n):
            pay_id += 1
            amt = base if k < n - 1 else round(total - base * (n - 1), 2)
            pay.append([pay_id, m["id"],
                        date(year - 1, 12, min(28, 1 + k * 7)) if k == 0
                        else date(year, 1 + k, min(28, 5 + k * 3)),
                        amt, random.choice(["Cash", "Debit", "Credit Card"]),
                        year, k + 1])
rows("Payments",
     ["paymentID", "memberID", "paymentDate", "amount", "method",
      "membershipYear", "installmentNumber"], pay)

# Teams: 2 Boys + 2 Girls per location
teams = []
tid = 0
teams_by_loc_gender = {}
SUFFIX = ["Lions", "Eagles", "Wolves", "Falcons"]
for lid, name, *_ in LOC_DEFS:
    short = name.split()[0]
    for gender in ("Boys", "Girls"):
        for k in range(2):
            tid += 1
            t = dict(id=tid, name=f"{short} {SUFFIX[k]} {gender}", gender=gender, loc=lid)
            teams.append(t)
            teams_by_loc_gender.setdefault((lid, gender), []).append(t)
rows("Teams", ["teamID", "teamName", "gender", "locationID"],
     [[t["id"], t["name"], t["gender"], t["loc"]] for t in teams])

# Team_Members: split each location/gender pool between its two teams
tm = []
for (lid, gender), pool in by_loc_gender.items():
    ts = teams_by_loc_gender[(lid, gender)]
    for i, m in enumerate(pool):
        t = ts[i % 2]
        tm.append([t["id"], m["id"], m["reg"], None])
        m["team"] = t["id"]
rows("Team_Members", ["teamID", "memberID", "startDate", "endDate"], tm)

# Sessions, formations, players
#
# Six games and four trainings per location, all in 2026 so they fall inside
# the reporting periods, plus future sessions next week for the email demo.
# Both sides of a session share a location and a gender. Two cross-location
# games are added at the end so that case is covered too.
sessions, formations, fplayers = [], [], []
sid = fmid = 0
busy = {}      # memberID -> list of datetimes already assigned

ROLES_MAIN = ["Goalkeeper", "Right fullback", "Sweeper", "Defending midfielder", "Striker"]
ROLES_EXTRA = ["Left fullback", "Center back", "Right winger", "Central midfielder",
               "Attacking midfielder", "Left winger"]


def can_place(m, when):
    for prev in busy.get(m["id"], []):
        if prev.date() == when.date() and abs((prev - when).total_seconds()) < 3 * 3600:
            return False
    return True


def place(m, when):
    busy.setdefault(m["id"], []).append(when)


def add_session(when, address, stype):
    global sid
    sid += 1
    sessions.append([sid, when, address, stype])
    return sid


def add_formation(session_id, team, coach_id, score):
    global fmid
    fmid += 1
    formations.append([fmid, session_id, team["id"], coach_id, score])
    return fmid


def roster(pool, when, size, want_win):
    """Players free at `when`, respecting the cohort flags."""
    out = []
    for m in pool:
        if len(out) >= size:
            break
        if m["never_formation"] or not m["active"]:
            continue
        if m["never_wins"] and want_win:
            continue
        if not can_place(m, when):
            continue
        out.append(m)
    return out


day = date(2026, 1, 10)
for lid, name, *_ in LOC_DEFS:
    loc_addr = [d[3] for d in LOC_DEFS if d[0] == lid][0]
    head_coaches = [p for p in dual_role if p["loc"] == lid] + \
                   [p for p in coaches_by_loc[lid] if p not in dual_role]
    n = 0
    for gender in ("Boys", "Girls"):
        ts = teams_by_loc_gender[(lid, gender)]
        pool = by_loc_gender[(lid, gender)]
        pool_a = [m for m in pool if m.get("team") == ts[0]["id"]]
        pool_b = [m for m in pool if m.get("team") == ts[1]["id"]]
        for k in range(5):                      # 3 games + 2 trainings per gender
            stype = "Game" if k < 3 else "Training"
            when = datetime.combine(day + timedelta(days=n * 9 + lid * 3),
                                    datetime.min.time()) + timedelta(hours=9 + (n % 3) * 4)
            n += 1
            s = add_session(when, f"{loc_addr}, {name} field {k + 1}", stype)
            if stype == "Game":
                sa, sb = random.choice([(2, 1), (0, 3), (1, 1), (4, 2), (2, 2), (1, 3)])
            else:
                sa = sb = None
            for team, pl, sc, opp in ((ts[0], pool_a, sa, sb), (ts[1], pool_b, sb, sa)):
                coach = head_coaches[(k + lid) % len(head_coaches)]
                f = add_formation(s, team, coach["id"], sc)
                want_win = (sc is not None and opp is not None and sc > opp)
                picked = roster(pl, when, 6, want_win)
                for i, m in enumerate(picked):
                    if m["only_gk"]:
                        role = "Goalkeeper"
                    elif m["all_five_roles"] and stype == "Game":
                        role = ROLES_MAIN[k % len(ROLES_MAIN)]
                    elif i == 0:
                        role = "Goalkeeper"
                    else:
                        role = (ROLES_MAIN + ROLES_EXTRA)[(i + k) % 11]
                    # one goalkeeper per formation
                    if role == "Goalkeeper" and any(r[2] == "Goalkeeper" for r in fplayers if r[0] == f):
                        role = ROLES_EXTRA[i % len(ROLES_EXTRA)]
                    fplayers.append([f, m["id"], role])
                    place(m, when)

# The report 16 cohort needs each of the five roles at least once in a game.
# Top up whatever the loop above missed.
need = {m["id"]: set(ROLES_MAIN) for m in members if m["all_five_roles"]}
game_forms = {}
for fid_, s_id, t_id, c_id, sc in formations:
    stype = [x[2] for x in sessions if x[0] == s_id][0]
    game_forms[fid_] = (s_id, t_id, sc)
for r in fplayers:
    if r[1] in need:
        need[r[1]].discard(r[2])

extra_day = date(2026, 6, 1)
for m in [x for x in members if x["all_five_roles"]]:
    missing = sorted(need.get(m["id"], set()))
    for j, role in enumerate(missing):
        when = datetime.combine(extra_day + timedelta(days=m["id"] % 20 + j * 2),
                                datetime.min.time()) + timedelta(hours=10)
        loc_addr = [d[3] for d in LOC_DEFS if d[0] == m["loc"]][0]
        s = add_session(when, f"{loc_addr}, top-up field", "Game")
        ts = teams_by_loc_gender[(m["loc"], m["gender"])]
        hc = [p for p in dual_role if p["loc"] == m["loc"]][0]
        f1 = add_formation(s, ts[0], hc["id"], 3)
        f2 = add_formation(s, ts[1], hc["id"], 1)
        target = f1 if m.get("team") == ts[0]["id"] else f2
        fplayers.append([target, m["id"], role])
        place(m, when)
        mates = [x for x in by_loc_gender[(m["loc"], m["gender"])]
                 if x is not m and not x["never_formation"] and x["active"]
                 and x.get("team") == m.get("team") and can_place(x, when)][:3]
        for i, x in enumerate(mates):
            fplayers.append([target, x["id"], ROLES_EXTRA[i]])
            place(x, when)

# Two cross-location games (teams from different locations).
for a, b in ((1, 2), (4, 5)):
    when = datetime(2026, 5, 16 + a, 13, 0, 0)
    s = add_session(when, "Parc Jarry, Montreal", "Game")
    ta = teams_by_loc_gender[(a, "Boys")][0]
    tb = teams_by_loc_gender[(b, "Boys")][0]
    ca = [p for p in dual_role if p["loc"] == a][0]
    cb = [p for p in dual_role if p["loc"] == b][0]
    fa = add_formation(s, ta, ca["id"], 2)
    fb = add_formation(s, tb, cb["id"], 0)
    for team_loc, f in ((a, fa), (b, fb)):
        pool = [m for m in by_loc_gender[(team_loc, "Boys")]
                if m.get("team") == (ta if team_loc == a else tb)["id"]
                and not m["never_formation"] and m["active"] and can_place(m, when)][:6]
        for i, m in enumerate(pool):
            fplayers.append([f, m["id"], (ROLES_MAIN + ROLES_EXTRA)[i]])
            place(m, when)

# Future sessions next week, for the email demo (score must be NULL).
for lid in (1, 2, 3):
    for gender in ("Boys", "Girls"):
        when = datetime(2026, 8, 9 + lid, 14 if gender == "Boys" else 18, 0, 0)
        loc_addr = [d[3] for d in LOC_DEFS if d[0] == lid][0]
        name = [d[1] for d in LOC_DEFS if d[0] == lid][0]
        s = add_session(when, f"{loc_addr}, {name} main pitch",
                        "Training" if lid == 2 else "Game")
        ts = teams_by_loc_gender[(lid, gender)]
        hc = [p for p in dual_role if p["loc"] == lid][0]
        f1 = add_formation(s, ts[0], hc["id"], None)
        f2 = add_formation(s, ts[1], hc["id"], None)
        for t, f in ((ts[0], f1), (ts[1], f2)):
            pool = [m for m in by_loc_gender[(lid, gender)]
                    if m.get("team") == t["id"] and not m["never_formation"]
                    and m["active"] and can_place(m, when)][:6]
            for i, m in enumerate(pool):
                role = "Goalkeeper" if i == 0 else (ROLES_MAIN + ROLES_EXTRA)[(i + 1) % 11]
                if m["only_gk"]:
                    role = "Goalkeeper"
                    if any(r[2] == "Goalkeeper" and r[0] == f for r in fplayers):
                        continue
                fplayers.append([f, m["id"], role])
                place(m, when)

rows("Sessions", ["sessionID", "startDateTime", "address", "sessionType"], sessions)
rows("TeamFormations", ["formationID", "sessionID", "teamID", "headCoachID", "score"], formations)
rows("FormationPlayers", ["formationID", "memberID", "playerRole"], fplayers)

# FIFA games and participation
fifa, gpart = [], []
gid = 0
OPP = ["FC Aurora", "Riverside United", "Northside FC", "Atlas Rovers",
       "Harbour City", "Granite SC", "Lakeshore FC", "Vertex United"]
CITIES = ["Toronto", "Ottawa", "Boston", "New York", "Halifax", "Vancouver"]

# Members with five or more FIFA games, for report 11.
heavy = []
for lid in (1, 2, 3, 4, 5, 6):
    cands = [m for m in members if m["loc"] == lid and not m["never_formation"]]
    heavy.append(cands[4])
    cands[4]["fifa_heavy"] = True

for m in heavy:
    for k in range(random.randint(5, 7)):
        gid += 1
        y = 2021 + k % 6
        sw, sa = random.choice([(3, 1), (0, 2), (2, 2), (4, 0), (1, 2)])
        fifa.append([gid, date(y, 1 + (k * 3) % 12, 10 + k), random.choice(CITIES),
                     f"{[d[1] for d in LOC_DEFS if d[0]==m['loc']][0]} Select",
                     random.choice(OPP), sw, sa])
        gpart.append([m["id"], gid])

# Members who never join a formation but do play FIFA, for report 13.
for m in [x for x in members if x["never_formation"] and x["active"]]:
    for k in range(random.randint(1, 3)):
        gid += 1
        sw, sa = random.choice([(2, 1), (1, 1), (0, 3)])
        fifa.append([gid, date(2024 + k % 3, 5 + k, 12), random.choice(CITIES),
                     f"{[d[1] for d in LOC_DEFS if d[0]==m['loc']][0]} Select",
                     random.choice(OPP), sw, sa])
        gpart.append([m["id"], gid])

# At least two FIFA players under the same primary family, for report 9.
fam_children = {}
for f_, m_, s_, e_, r_ in frel:
    fam_children.setdefault(f_, []).append(m_)
paired = 0
for f_, kids in fam_children.items():
    if paired >= 10 or len(kids) < 2:
        continue
    for m_ in kids[:2]:
        gid += 1
        fifa.append([gid, date(2025, 3 + paired % 6, 8), random.choice(CITIES),
                     "Club Select", random.choice(OPP), 2, 1])
        gpart.append([m_, gid])
    paired += 1

# A spread so every location has at least two FIFA participants.
for m in random.sample([x for x in members if not x["fifa_heavy"]], 60):
    gid += 1
    sw, sa = random.choice([(1, 0), (2, 3), (1, 1)])
    fifa.append([gid, date(random.randint(2023, 2026), random.randint(1, 12),
                           random.randint(1, 28)), random.choice(CITIES),
                 f"{[d[1] for d in LOC_DEFS if d[0]==m['loc']][0]} Select",
                 random.choice(OPP), sw, sa])
    gpart.append([m["id"], gid])

seen = set()
gpart = [g for g in gpart if not (tuple(g) in seen or seen.add(tuple(g)))]

rows("FIFA_Games",
     ["gameID", "gameDate", "gameLocation", "teamWith", "teamAgainst",
      "scoreWith", "scoreAgainst"], fifa)
rows("Game_Participation", ["memberID", "gameID"], gpart)

# Generate the email log for next week's sessions
w("-- Fill EmailLogs by running the weekly batch for Sunday 9 August 2026.")
w("CALL sp_GenerateWeeklyEmails('2026-08-09');")
w()

with open("/home/claude/cscs/database/seed.sql", "w") as fh:
    fh.write("\n".join(OUT))

print(f"locations={len(loc_rows)} personnel={len(personnel)} families={len(families)} "
      f"members={len(members)} teams={len(teams)} sessions={len(sessions)} "
      f"formations={len(formations)} formationPlayers={len(fplayers)} "
      f"fifa={len(fifa)} participation={len(gpart)} payments={len(pay)}")
